config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signin", to: "sessions#new"
  post '/signin' => 'sessions#create'
  #post "/sessions/create", to: "sessions#create"
  get '/auth/developer/callback', to: 'sessions#create'
  delete "/signout", to: "sessions#destroy"
  post "/decks/new", to: "decks#new"
  post "/games/save", to: "games#save"
  post "/games/delete", to: "games#delete"
  post "/decks/:id/delete", to: "decks#destroy"
  post"/users/:id/delete", to: "users#destroy"
  get"/users/:id/decks_index", to: "users#decks_index"
  get '/auth/google_oauth2/callback' => 'sessions#gcreate'
  #get '/auth/facebook/callback' => 'sessions#gcreate'
  post '/decks/:deck_id/games', to: "games#create"
  get '/decks/wlratio', to: "decks#good"
  get '/users/same', to: "users#same"
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :decks do
    resources :games
  end
  resources :games
  #resources :ccgs
  resources :users
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/views/static_pages/home.html.erb
  
<div class="home">
  <div class="home--header-box">
    <h1 class="heading-primary">Deck Tracker</h1>
  
    <div class="home--links">
      <%= link_to "Sign in", signin_path, class:"btn btn__left btn__green" %>
      <%= link_to "Sign Up", new_user_path, class: "btn btn__green" %>
      <div class="google-login">
        <%= link_to('/auth/google_oauth2', class: "btn__green btn__disabled") do %>
          <span class="btn-content"><%=image_tag "google.png", class: "icon"%> Login</span>
          <% end %>
      </div>
    </div>
    </div>
</div>