config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signin", to: "sessions#new"
  post '/signin' => 'sessions#create'
  #post "/sessions/create", to: "sessions#create"
  get '/auth/developer/callback', to: 'sessions#create'
  delete "/signout", to: "sessions#destroy"
  post "/decks/new", to: "decks#new"
  post "/games/save", to: "games#save"
  post "/games/delete", to: "games#delete"
  post "/decks/:id/delete", to: "decks#destroy"
  post"/users/:id/delete", to: "users#destroy"
  get"/users/:id/decks_index", to: "users#decks_index"
  get '/auth/google_oauth2/callback' => 'sessions#gcreate'
  #get '/auth/facebook/callback' => 'sessions#gcreate'
  post '/decks/:deck_id/games', to: "games#create"
  get '/decks/wlratio', to: "decks#good"
  get '/users/same', to: "users#same"
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :decks do
    resources :games
  end
  resources :games
  #resources :ccgs
  resources :users
end

app/models/game.rb
class Game < ActiveRecord::Base
    belongs_to :deck
    belongs_to :user
    has_many :game_tags
    has_many :tags, through: :game_tags
    validates :result, presence: true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :set_deck, only: [:index, :new]
    def show
    end
    
    def index
        if @deck
          @games=current_user.games.where(deck: @deck).select{|g| g.created_at.today?}
        else
          @games=current_user.games.select{|g| g.created_at.today?}
        end
        @last_game=@games.last
        @games.reverse!
        #binding.pry
        if (@games.length==0)
          respond_to do |format|
            if(!!@deck)
              format.html { redirect_to new_deck_game_path, notice: 'No recent games' }
            else
              format.html { redirect_to new_game_path, notice: 'No recent games' }
            end
          end
        end
    end

    def new
      @game=Game.new
      @decks=current_user.decks  
    end

    def delete
      current_user.games.last.destroy
      respond_to do |format|
        format.html { redirect_to games_path, notice: 'Game was deleted' }
      end
    end

    def show
      @game=Game.find(params[:id])
    end

    def create
      if params[:deck_id]!=nil
        set_deck
        @game=Game.new(game_params)
        @game.deck_id=@deck.id
        @game.user_id=current_user.id
        @route="/decks/#{@deck.id}/games/new"
      elsif params[:action]=="create"&& params[:game][:deck_id]!=""
        @game=Game.new(game_params)
        @route="/games/new"
        @deck=Deck.find(id=@game.deck_id)
        @game.user_id=current_user.id
      else
          @route="/games/new"
          @decks=current_user.decks
      end
      respond_to do |format|
        if (!!@game)
          make_tags(@game)      
        
          if @game.save
              @deck.record_game(@game.result)
              @game=Game.new
              @decks=current_user.decks
              format.html { redirect_to @route, notice: 'Game was successfully recorded.' }
            else
              @decks=current_user.decks
              format.html { redirect_to @route, notice: 'Game was not recorded, you need to select a result' }
          end
        
        else 
          @decks=current_user.decks
          format.html { redirect_to @route, notice: 'Game was not recorded, you need to select a result' }
        end
      end
    end
    
    def good
    end

    private
      def make_tags(arg)
        arg.tag_ids=params[:game][:tag_ids]
      end

      def set_deck
        @deck=Deck.find_by_id(params[:deck_id])
      end
      def get_deck
        @deck=Deck.find_by_id(params[:game][:deck_id])
      end

      def game_params
        params.require(:game).permit(
        :user_id,
        :deck_id,
        :result,
        :tag_ids,
        :comment,
        :opponent_deck
        )
      end
end

app/views/games/_deckform.html.erb
<%= form_for [@deck, @game] do |g| %>
  
    <div class="form u-center-text">
        <div class="form-group header">Deck: <%=@deck.name%>&nbsp;<%= link_to 'Use a different deck', new_game_path, class: "btn btn__green"%></div>
        <div class="form-group form-group__radio">
            <label class="form__label form__label__static">Result:</label>
            <%= g.radio_button(:result, "Win",:class=>"game-win") %>
            <%= label_tag(:game_result_win, "Win",:class=>"radio radio__game-win") %>
            <%= g.radio_button(:result, "Loss", :class=>"game-loss") %>
            <%= label_tag(:game_result_loss, "Loss",:class=>"radio radio__game-loss") %>
        </div>
        <%= render 'optional', g: g %>
        <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
            <%= tag(:input, :type => "hidden", :name => :user_id, :value => current_user.id) %>
            <input class= "btn btn__white btn__center" type="submit" Id="submitGame" value="Record Game" >
        
    </div>
<%end%>

app/views/games/_form.html.erb
    <%= form_for @game do |g| %>  
    <div class="form u-center-text">
    <div class="form-group header">Play a game! 
        <%= link_to 'View Games', games_path, class: "btn btn__white" %></div>
        <div class="form-group form-group__select">
        <label class="form__label form__label__static">Deck:</label>
            <%= g.collection_select(:deck_id, @decks, :id, :name, {include_blank:"Select a Deck"}) %>
        </div>
        <div class="form-group form-group__radio">
            <label class="form__label form__label__static">Result:</label>
            <%= g.radio_button(:result, "Win",:class=>"game-win") %>
            <%= label_tag(:game_result_win, "Win",:class=>"radio radio__game-win") %>
            <%= g.radio_button(:result, "Loss", :class=>"game-loss") %>
            <%= label_tag(:game_result_loss, "Loss",:class=>"radio radio__game-loss") %>
        </div>
        <%= render 'optional', g: g %>
        
        <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
            <%= tag(:input, :type => "hidden", :name => :user_id, :value => current_user.id) %>
        <input class= "btn btn__white btn__center" type="submit" Id="submitGame" value="Record Game" >
    </div>
<%end%>

app/views/games/_optional.html.erb
<%= button_tag "Optional", type: 'button', onclick: "showGameOptions()", class: 'btn', id: "modalButton" %>
<div class="modal" id="optionalModal">    
    <div class="header u-margin-bot-md">Optional</div>
        <div class="row form-group__textarea">
            <%= g.text_area :comment, class: "form__input", placeholder: "Comments" %>
            <%= g.label :Comments, class: "form__label" %>
        </div>
        <div class="row form-group__text">
            <%= g.text_field :opponent_deck, class: "form__input", :placeholder =>"Opponent's deck"%>
            <%= g.label :opponent_deck, "Opponent's deck", class: "form__label" %>
        </div>
    <div class="row header u-margin-bot-sm">Tags</div>
    <div class="row">
        <%= g.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |c| %>
            <%= c.label(class: "ccg_label") do %>
                <%= c.check_box(class: "check_box") %>
                <%= c.object.name %>
            <% end %>
        <%end%>
    </div>
</div>

app/views/games/index.html.erb
<div class="game">
    <h2 class="header">Play a game! </h2>
    <% if @deck %>
        <%= link_to 'Play Games!', new_deck_game_path(@deck), class: "btn btn__green" %>
    <%else%>
        <%= link_to 'Play Games!', new_game_path, class: "btn btn__green" %>
    <%end%>
    <% if @games%>
        <table>
        <tr>
        <th class="game__header game__header__deck">Deck</th>
        <th class="game__header game__header__result">W/L</th>
        <th class="game__header game__header__tags">Tags</th>
        <th class="game__header game__header__comments">Comments</th>
        </tr>
            <%@games.each do |game| %>     
                <% if game==@last_game%>
                        <form action="/games/delete" method="POST"><input class="btn btn__danger" type="submit" value="Delete Most Recent Game">
                            <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
                            <%= tag(:input, :type => "hidden", :name => :user_id, :value => current_user.id) %>
                        </form>

                        <%if game.deck%>
                            <td class="game__deck"><%= link_to "#{game.deck.name}", game_path(game), class: "game__deck game__deck_link" %></td>
                            <%if (game.result=="Win") %>
                                <td class="game__result game__result_win">W</td>
                            <%else%>
                                <td class="game__result game__result_loss">L</td>
                            <%end%>
                            <td class="game__tags">
                                <%game.tags.each do |tag|%>
                                    <%=tag.name%>
                                <%end%>
                            </td>
                            <td class="game__comments">
                                <%if game.comment%>
                                    <%=game.comment%>
                                <%end%>
                            </td>
                        <%else%>
                            Deck was deleted: <%=game.result %> 
                        <%end%>
                <%else%>
                    <%if game.deck%>
                    <tr>
                        <td class="game__deck"><%= link_to "#{game.deck.name}", game_path(game), class: "game__deck game__deck_link" %></td>
                        <%if (game.result=="Win") %>
                            <td class="game__result game__result_win">W</td>
                        <%else%>
                            <td class="game__result game__result_loss">L</td>
                        <%end%>
                        <td class="game__tags">
                            <%game.tags.each do |tag|%>
                                <%=tag.name%>
                            <%end%>
                        </td>
                        <td class="game__comments">
                            <%if game.comment%>
                                <%=game.comment%>
                            <%end%>
                        </td>
                    <%else%>
                        Deck was deleted: <%=game.result %> 
                    <%end%>
                    </tr>
                <%end%>
                        
            <%end%>
        </table>
    <%end%>
</div>

app/views/games/new.html.erb
<% if @deck %>
    <%= render 'deckform'%>
<%else%>
    <%if current_user.decks.length>0%>
        <%= render 'form'%>
    <%else%>
        <h2 class="header u-alert-text">You need a deck to play a game! <%= link_to 'New Deck', new_deck_path(current_user) %></h2>
        
    <%end%>
<%end%>

app/views/games/show.html.erb
<div class="game">
            <div class="row"><div class="game__show">Deck Name:<div class="game__show_deck"> <%= @game.deck.name %></div></div></div>
            <div class="row"><div class="game__show">Game:<div class="game__show_game"> <%= @game.deck.ccg.name %></div></div></div>
            <div class="row"><div class="game__show">Result:<div class="game__show_result"> <%= @game.result %></div></div></div>
            <%if @game.opponent_deck!="" %>
               <div class="game__show">Opponent Deck:<div class="game__show_deck"> <%= @game.opponent_deck %></div></div>
            <%end%>
            <%if @game.comment!="" %>
               <div class="game__show">Comments:<div class="game__show_comments"> <%= @game.comment %></div></div>
            <%end%>
            <div class="game__show">
               Tags:
               <% @game.tags.each do |tag|%>
                  <div class="game__show_tags"><%=tag.name%></div>
               <%end%>
            </div>

</div>