config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signin", to: "sessions#new"
  post '/signin' => 'sessions#create'
  #post "/sessions/create", to: "sessions#create"
  get '/auth/developer/callback', to: 'sessions#create'
  delete "/signout", to: "sessions#destroy"
  post "/decks/new", to: "decks#new"
  post "/games/save", to: "games#save"
  post "/games/delete", to: "games#delete"
  post "/decks/:id/delete", to: "decks#destroy"
  post"/users/:id/delete", to: "users#destroy"
  get"/users/:id/decks_index", to: "users#decks_index"
  get '/auth/google_oauth2/callback' => 'sessions#gcreate'
  #get '/auth/facebook/callback' => 'sessions#gcreate'
  post '/decks/:deck_id/games', to: "games#create"
  get '/decks/wlratio', to: "decks#good"
  get '/users/same', to: "users#same"
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :decks do
    resources :games
  end
  resources :games
  #resources :ccgs
  resources :users
end

app/models/deck.rb
class Deck < ActiveRecord::Base
    belongs_to :ccg
    has_many :games
    belongs_to :user
    has_many :games
    has_many :tags, through: :games
    validates :name, presence: true
    validates :ccg, presence: true
    scope :wlratio, -> {where("decks.wins>decks.losses")} 
    # enum color: [
    #     :Colorless,
    #     :White,
    #     :Blue,
    #     :Black,
    #     :Red,
    #     :Green

    # ]
    enum color: {
        Colorless: 0,
        White: 1,    
        Blue: 2,
        Black: 3,
        Red: 4,
        Green: 5,
        Azorious: 6,
        Dimir: 7,
        Rakdos: 8,
        Gruul: 9,
        Selesnya: 10,
        Orzhov: 11,
        Izzet: 12,
        Golgari: 13,
        Boros: 14,
        Simic: 15,
        #Shards
        Bant: 16,
        Esper: 17,
        Grixis: 18,
        Jund: 19,
        Naya: 20,
        #Wedges
        Abzan: 21,
        Jeskai: 22,
        Sultai: 23,
        Mardu: 24,
        Temur: 25,
        #4 colors
        UBRG: 26,
        WBRG: 27,
        WURG: 28,
        WUBG: 29,
        WUBR: 30,
        #5 color
        WUBRG: 31
    }
    def record_game(result)
        if result == "Win" 
            self.update(:wins=> self.wins+=1)
        else
            self.update(:losses=> self.losses+=1)
        end
    end

    def short_link
        if self.link!=""||nil
            if self.link.split('.').length==3
                self.link.split('.')[1]
            elsif self.link.split('.').length==2
                self.link.split('.')[0].split('/')[2]
            else
                "Link is Suspicious: Be Wary"
            end
        end
    end
    def tag_count
        tags=[]
        self.games.each do |game|
            game.tags.each do |tag|
                tags << tag  
            end
        end
        tags  
    end




end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
    before_action :set_deck, only: [:show, :edit, :update, :destroy]
    def index
        @decks=current_user.decks
        @user=current_user
    end

    def show
        @tags=@deck.tag_count
    end

    def edit
        @deck = Deck.find(params[:id])
    end

    def new
        @deck=Deck.new
    end

    def create
        @deck= Deck.new(deck_params)
        @deck.user_id=current_user.id
        @deck.wins=0
        @deck.losses=0
        respond_to do |format|
            if @deck.save
              format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
            else
              format.html { redirect_to new_deck_url, notice: "Deck was not created, the name can't be blank"}
            end
          end
    end
    
    def update
        respond_to do |format|
            if @deck.update(deck_params)
              format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
            else
              format.html { render :edit }
            end
        end
    end

    def destroy
        @deck.destroy
        respond_to do |format|
          format.html { redirect_to decks_url, notice: 'Deck was successfully deleted.' }
        end
    end
    
    def good
        @user=current_user
    end
    
    private
    def set_deck
        @deck=Deck.find(params[:id])
    end
    def set_colors
        @colors = Colors.new()
    end

    def deck_params
        params.require(:deck).permit(
            :name,
            :ccg_id,
            :link,
            :color
        )
    end
end

app/views/decks/_decks.html.erb
<div class="row deck__links">
  <% if user!=current_user %>
    <%= link_to "Back to profile", user_path(user), :class => "btn btn__blue" %>
    <% else %>
    <%= link_to 'Decks with more wins than losses', decks_wlratio_path,class: "btn btn__black" %>
      <%= link_to 'New Deck', new_deck_path, class: "btn btn__blue" %>
  <% end %>
  <%= link_to 'Play some Games!', games_path, class: "btn btn__green" %>
</div>

<div class="header u-margin-bot-sm u-center-text"> <%=user.Username%>'s Decks </div>
<% decks.each do |deck| %>
    <div class="row">
      <%= link_to "#{deck.name}", deck_path(deck), class: "btn btn__art"   %>
    </div>
  <% end %>

app/views/decks/_form.html.erb
<%= form_for(@deck) do |d| %>  
  <%= d.text_field :name, class: "form__input", placeholder: "Name" %>
  <%= d.label :name, class: "form__label" %>  
  <%= d.label :ccg, "Format", class:"col-1-of-2 form__label form__label__static"  %>
  <%= d.collection_select(:ccg_id, current_user.ccgs, :id, :name) %>
  <%= d.label :ccg, "Colors", class:"form__label form__label__static"  %>    
  <%= d.select(:color, Deck.colors.keys.map {|color| [color,color]}) %>
  <%= d.text_field :link, class: "form__input", placeholder: "Optional link to the deck" %>
  <%= d.label :link, "Link:", class: "form__label" %>
  <%= d.submit class: "btn btn__white btn__center" %>
<% end %>

app/views/decks/edit.html.erb
<div class="form">
<form class="u-center-text" action="delete" method="POST"><h2 class="header" >Edit</h2> - <input type="submit" value="Delete Deck", class="btn btn__danger">
        <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
                <%= tag(:input, :type => "hidden", :name => :user_id, :value => current_user.id) %>
        </form>
        
        <%= render 'form' %>
        
</div>

app/views/decks/good.html.erb
<div class="deck"> <h2 class="header u-margin-bot-sm">Decks with more wins than losses</h2>
    <%= render partial: 'decks/decks', locals: {user:current_user, decks:current_user.decks.wlratio} %>
</div>

app/views/decks/index.html.erb
<div class="deck">
    <% if @user %>
        <%= render partial: 'decks/decks', locals: {user:@user, decks:@user.decks} %>
    <%else%>
        <%= render partial: 'decks/decks', locals: {user:current_user, decks:current_user.decks} %>
    <%end%>
</div>

app/views/decks/new.html.erb
<div class="form form__deck">
    <h2 class="header">New Deck</h2>
    <%if current_user.ccgs.length>0%>
        <%= render 'form' %>
    <%else%>
        <h3 class="header u-alert-text">You need to choose at least one format you play in order to create decks</h3>
        <%= link_to 'Edit User', edit_user_path(current_user), class: "btn btn__blue" %>
    <%end%>
</div>

app/views/decks/show.html.erb
<div class="deck">
    <% if current_user.id==@deck.user_id %>
        <%= link_to 'Edit Deck', [:edit, @deck], class: "btn btn__red" %>
    <%end%>
    
        <div class="deck__name">Deck Name: <%= @deck.name %></div>
        <div class="deck__ccg">Game: <%= @deck.ccg.name %></div>
        <div class="deck__wins">Wins: <%= @deck.wins %></div>
        <div class="deck__losses">Losses: <%= @deck.losses %></div>
        <% if @deck.link != "" %>
            <div class = "deck__link">Link: <a href=<%=@deck.link%> target="_blank" ><%=@deck.short_link%></a></div>
        <%end%>
        Tags:
        <ul class="tags">
        <%@tags.each do |tag| %>
            <li class="row"><%= tag.name%>:<%= @tags.count(tag) %></li>
        <%end%>
        </ul>
        <div class="row deck__links">
        <%= link_to 'Play some Games!', deck_games_path(@deck.id), class: "btn btn__green" %>
        <%= link_to 'Back to decks list', decks_path,class: "btn btn__black" %> 
        </div>
    
</div>