config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signin", to: "sessions#new"
  post '/signin' => 'sessions#create'
  #post "/sessions/create", to: "sessions#create"
  get '/auth/developer/callback', to: 'sessions#create'
  delete "/signout", to: "sessions#destroy"
  post "/decks/new", to: "decks#new"
  post "/games/save", to: "games#save"
  post "/games/delete", to: "games#delete"
  post "/decks/:id/delete", to: "decks#destroy"
  post"/users/:id/delete", to: "users#destroy"
  get"/users/:id/decks_index", to: "users#decks_index"
  get '/auth/google_oauth2/callback' => 'sessions#gcreate'
  #get '/auth/facebook/callback' => 'sessions#gcreate'
  post '/decks/:deck_id/games', to: "games#create"
  get '/decks/wlratio', to: "decks#good"
  get '/users/same', to: "users#same"
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :decks do
    resources :games
  end
  resources :games
  #resources :ccgs
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CCG Tracker</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css2?family=Aclonica&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <div class="bg-video">      
          <%= video_tag "bg.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "bg-video__content" %>      
      </div>
    
      <div class="mana-container">
            <div class="mana">
              <figure class="mana__figure mana__figure-w">
              <% if !logged_in? %>
                <a href="<%= root_url %>">
              <% else %>
                <a href="<%= user_path(current_user) %>" >
              <%end%>
                  <%= image_tag("W.svg", :alt=>"W", :class=>"mana__img") %>
                  <figcaption class="mana__text">Home</figcaption>
                </a>
              </figure>
            </div>
            <div class="mana">
              <figure class="mana__figure mana__figure-u">
                <a href="<%=games_path%>" >
                  <%= image_tag("U.svg", :alt=>"U", :class=>"mana__img") %>
                  <figcaption class="mana__text">Play</figcaption>
                </a>
              </figure>
            </div>
            <div class="mana">
              <figure class="mana__figure mana__figure-b">
                <a href="<%=decks_path%>" >
                  <%= image_tag("B.svg", :alt=>"B", :class=>"mana__img") %>
                  <figcaption class="mana__text">Decks</figcaption>
                </a>
              </figure>
            </div>
            <div class="mana">
              <figure class="mana__figure mana__figure-r">
                <a href="<%=users_path%>" >
                  <%= image_tag("R.svg", :alt=>"R", :class=>"mana__img") %>
                  <figcaption class="mana__text">Browse</figcaption>
                </a>
              </figure>
            </div>
            <div class="mana">
              <figure class="mana__figure mana__figure-g">
                <a data-method="delete" href="<%= signout_path %>">
                  <%= image_tag("G.svg", :alt=>"G", :class=>"mana__img") %>
                  <figcaption class="mana__text" >Logout</figcaption>
                </a>
              </figure>
              
          </div>
    </div>

    <!-- content -->
    <div class="body"  role="main">
      <div class="main">
        <div class="application">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>